python -m lerobot.record \
    --robot.type=so101_follower \
    --robot.port=/dev/ttyACM1 \
    --robot.id=slave \
    --robot.cameras="{ front: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --teleop.type=so101_leader \
    --teleop.port=/dev/ttyACM0 \
    --teleop.id=master \
    --display_data=true \
    --dataset.repo_id=islab/my_dataset \
    --dataset.root=/home/isl-so100/Desktop/disk/test_data_2 \
    --dataset.num_episodes=2 \
    --dataset.fps=30 \
    --dataset.episode_time_s=10 \
    --dataset.reset_time_s=10 \
    --dataset.single_task="Grab the black cube"